
services:
  webapi:
    build:
      context: .
      dockerfile: VoterSystem.WebAPI/Dockerfile
    container_name: webapi
    ports:
      - "6900:6900"
    environment:
      - ASPNETCORE_URLS=http://+:6900
    restart: unless-stopped
    networks:
      - votersystem-internal-network


  web:
    build:
      context: .
      dockerfile: VoterSystem.Web/Dockerfile
    container_name: web
    ports:
      - "6901:6901"
    environment:
      - ASPNETCORE_URLS=http://+:6901
    restart: unless-stopped
    networks:
      - votersystem-internal-network

  admin:
    build:
      context: .
      dockerfile: VoterSystem.Web.Admin/Dockerfile
    container_name: admin
    ports:
      - "6902:6902"
    environment:
      - ASPNETCORE_URLS=http://+:6902
    restart: unless-stopped
    networks:
      - votersystem-internal-network

networks:
  votersystem-internal-network:
     name: votersystem_internal_network
