
services:
  db:
    image: mariadb:11.4.2-noble
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./configs/db/:/docker-entrypoint-initdb.d/
      - ./data/db/:/var/lib/mysql/
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - votersystem-internal-network
    restart: unless-stopped
        
  webapi:
    build:
      context: .
      dockerfile: VoterSystem.WebAPI/Dockerfile
    container_name: webapi
    ports:
      - "6900:6900"
    environment:
      - ASPNETCORE_URLS=http://+:6900
    restart: unless-stopped
    depends_on:
       db:
         condition: service_healthy

    networks:
      - votersystem-internal-network


  web:
    build:
      context: .
      dockerfile: VoterSystem.Web/Dockerfile
    container_name: web
    ports:
      - "6901:6901"
    environment:
      - ASPNETCORE_URLS=http://+:6901
    restart: unless-stopped
    networks:
      - votersystem-internal-network

  admin:
    build:
      context: .
      dockerfile: VoterSystem.Web.Admin/Dockerfile
    container_name: admin
    ports:
      - "6902:6902"
    environment:
      - ASPNETCORE_URLS=http://+:6902
    restart: unless-stopped
    networks:
      - votersystem-internal-network

networks:
  votersystem-internal-network:
     name: votersystem_internal_network
