
services:
  webapi:
    build:
      context: VoterSystem.WebAPI/
      dockerfile: Dockerfile
    container_name: webapi
    ports:
      - "6900:6900"
    environment:
      - ASPNETCORE_URLS=http://+:6900
    restart: always

  web:
    build:
      context: VoterSystem.Web/
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "6901:6901"
    environment:
      - ASPNETCORE_URLS=http://+:6901
    restart: always

  admin:
    build:
      context: VoterSystem.Web.Admin/
      dockerfile: Dockerfile
    container_name: admin
    ports:
      - "6902:6902"
    environment:
      - ASPNETCORE_URLS=http://+:6902
    restart: always
