
services:
  db:
    image: postgres:17.4
    environment:
        DB_USER: ${MYSQL_USER}
        DB_PASSWORD: ${MYSQL_PASSWORD}
        POSTGRES_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
        - ./backend/docker/initSQL/:/docker-entrypoint-initdb.d/
        - ./data/db/:/var/lib/postgresql/data
    restart: unless-stopped
    depends_on:
      init:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d VoterSystem" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    ports:
        - "3306:3306"
