
services:
  db:
    image: mariadb:11.4.2-noble
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./configs/db/:/docker-entrypoint-initdb.d/
      - ./data/db/:/var/lib/mysql/
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    restart: unless-stopped
    ports:
        - "3306:3306"
