services:
  db-base:
    image: postgres:18-trixie
    environment:
        POSTGRES_USER: ${DB_USER:?Please set the db user in .env}
        POSTGRES_PASSWORD: ${DB_PASSWORD:?Please set the db password in .env}
        POSTGRES_DB: NovaChatDb
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d NovaChatDb"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - votersystem-internal-network
    command: ["postgres", "-c", "max_connections=5000"]

  db-backup:
    image: prodrigestivill/postgres-backup-local:18
    restart: unless-stopped
    environment:
      POSTGRES_HOST: db-prod
      POSTGRES_USER: ${DB_USER:?Please set the db user in .env}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Please set the db password in .env}
      POSTGRES_DB: "NovaChatDb"
      SCHEDULE: "0 1 * * *"
      BACKUP_KEEP_DAYS: 7
      BACKUP_DIR: /backups
      COMPRESS: "gzip"
      POSTGRES_EXTRA_OPTS: "--clean --if-exists"
    volumes:
      - ../backups/db:/backups
    networks:
      - votersystem-internal-network
